using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IceScheduler.Slots
{
    public enum Rink
    {
        Unknown,  // Useful for conflict games
        Igloo,
        Garage,
        Pond,
        Coliseum,
        Forum,
        Gardens,
        Silver,
        Stadium,
        OvalNorth,
        OvalSouth,
        BuckNEar,
        AbbotsfordCentreArena,
        AbbotsfordARC,
        AbbotsfordCentreIceBlue,
        AbbotsfordMRC,
        AbbotsfordMSA,
        Agrodome,
        BellinghamSportsplex,
        BurnabyLake,
        BurnabyWinterClub,
        ChilliwackTwin2,
        Cloverdale,
        CoquitlamMain,
        CoquitlamRec,
        ExcellentIceBlue,
        GeorgePreston,
        HarryJerome,
        Hillcrest,
        IceSportsNorthShoreBlue,
        IceSportsNorthShoreGreen,
        IceSportsNorthShoreRed,
        Kensington,
        Killarney,
        LangleySportsplex1,
        LangleySportsplex2,
        LangleySportsplex4,
        LangleyTwin1,
        LangleyTwin2,
        LangleyEventsCentre,
        Newton,
        NorthShoreWinterClub,
        NorthSurrey2,
        PittMeadowsBlue,
        PittMeadowsRed,
        PlanetIceCoquitlam1,
        PlanetIceCoquitlam2,
        PlanetIceCoquitlam3,
        PlanetIceCoquitlam4,
        PlanetIceDeltaCanadian,
        PlanetIceMapleRidge1,
        PlanetIceMapleRidge2,
        PocoBlue,
        PocoGreen,
        PortMoody2,
        SouthDeltaTsawwassen,
        Sunset,
        SurreyLeisure1,
        SurreyLeisure2,
        SurreyLeisure3,
        Tilbury,
        TroutLake,
        WestVan,
    }
}
